[tool.poetry]
name = "fixcli"
version = "0.1.0"
description = ""
authors = ["williamguilhermesouza <williamguilhermesouza@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
quickfix = "^1.16.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
